source 'https://rubygems.org'
ruby '2.7.1'
gem 'bundler'
gem 'rspec'
gem 'pry'
gem 'nokogiri'
gem 'open-uri'
gem 'watir'
gem 'rubocop', '~> 0.57.2'
gem 'launchy'
gem 'json'
gem 'sinatra'
gem 'shotgun'
